shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms
from .models import Order
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserUpdateForm(UserCreationForm):
    tel = forms.CharField(max_length=20, required=False)
    avatar = forms.ImageField(required=False)
    # username = forms.CharField(max_length=100)
    # email = forms.EmailField(required=False)
    # password1 = forms.CharField(widget=forms.PasswordInput())
    # password2 = forms.CharField(widget=forms.PasswordInput())
    # first_name = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ('username', 'tel', 'email', 'first_name', 'avatar', 'password1', 'password2')


class UserRegistrationForm(UserCreationForm):
    tel = forms.CharField(max_length=20, required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'tel', 'email', 'password1', 'password2')


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = (
             'address', 'payment_method',  'city', 'delivery_method'
        )


class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RestorePasswordForm(forms.Form):
    email = forms.EmailField()

templates/users/about.html
{% extends "header-footer.html" %}
{% load static%}
<!--END-->
<!--END--><!DOCTYPE html><!--[if IE 7]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> <html lang="ru"> <!--<![endif]-->
{% block header %}{% endblock header %}
{% block footer %}{% endblock footer %}
{% block content %}
<body class="Site">
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">About Megano
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>About Us</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft Section_columnWide">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image"><img src='{% static "assets/img/icons/advantages/shipping.svg" %}' alt="shipping.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">Shipping & Returns
                </strong>
                <p class="media-text">World wide shipping
                </p>
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image"><img src='{% static "assets/img/icons/advantages/moneyBack.svg" %}' alt="moneyBack.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">Money Back
                </strong>
                <p class="media-text">Guaranted payments
                </p>
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image"><img src='{% static "assets/img/icons/advantages/support.svg" %}' alt="support.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">Support Policy
                </strong>
                <p class="media-text">Fast support team
                </p>
              </div>
            </div>
          </div>
          <div class="Section-columnSection Section-columnSection_mark">
            <div class="media media_advantage">
              <div class="media-image"><img src='{% static "assets/img/icons/advantages/quality.svg" %}' alt="quality.svg"/>
              </div>
              <div class="media-content">
                <strong class="media-title">Quality Guarantee
                </strong>
                <p class="media-text">Best guaranted items
                </p>
              </div>
            </div>
          </div>
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Follow Us
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="Footer-payments Footer-payments_column">
                <div><img src='{% static "assets/img/icons/socialContent/fb.png" %}' alt="fb.png"/>
                </div>
                <div><img src='{% static "assets/img/icons/socialContent/tw.png" %}' alt="tw.png"/>
                </div>
                <div><img src='{% static "assets/img/icons/socialContent/gg.png" %}' alt="gg.png"/>
                </div>
                <div><img src='{% static "assets/img/icons/socialContent/in.png" %}' alt="in.png"/>
                </div>
                <div><img src='{% static "assets/img/icons/socialContent/pt.png" %}' alt="pt.png"/>
                </div>
                <div><img src='{% static "assets/img/icons/socialContent/ml.png" %}' alt="ml.png"/>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <article class="Article">
            <div class="Article-section">
              <div class="row row_verticalCenter row_maxHalf">
                <div class="row-block">
                  <h2>Why Choose Megano?
                  </h2>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. Aenean massa. Cumtipsu sociis natoque penatibus et magnis dis parturient montesti, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eutu, pretiumem.
                  </p>
                  <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justotuio, rhoncus ut loret, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus element semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae  ligula eget dolor. Aenean massa. Cumtipsu sociis natoque pena tibusetm t semper ni.
                  </p>
                  <div><a class="btn btn_primary" href="#">Get Started</a>
                  </div>
                </div>
                <div class="row-block">
                  <div class="pict"><img src='{% static "assets/img/content/home/slider.png" %}' alt="slider.png"/>
                  </div>
                </div>
              </div>
            </div>
            <div class="Article-section">
              <div class="row row_verticalCenter row_maxHalf">
                <div class="row-block">
                  <div class="pict"><img src='{% static "assets/img/content/home/bigGoods.png" %}' alt="bigGoods.png"/>
                  </div>
                </div>
                <div class="row-block">
                  <h2>Megano Store Hystory
                  </h2>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. Aenean massa. Cumtipsu sociis natoque penatibus et magnis dis parturient montesti, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eutu, pretiumem.
                  </p>
                  <ul>
                    <li>Lorem ipsum dolor sit amet, consectetuer
                    </li>
                    <li>adipiscing elit doli. Aenean commodo ligula
                    </li>
                    <li>eget dolor. Aenean massa. Cumtipsu sociis
                    </li>
                    <li>natoque penatibus et magnis dis parturient
                    </li>
                    <li>montesti, nascetur ridiculus mus. Donec
                    </li>
                    <li>quam felis, ultricies nec, pellentesque eutu
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
</body></html>

templates/users/account.html
{% extends "header-footer.html" %}
{% load static%}
<!--END-->
<!--END--><!DOCTYPE html><!--[if IE 7]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> <html lang="ru"> <!--<![endif]-->
{% block header %}<{% endblock header %}
{% block footer %}<{% endblock footer %}
{% block content %}
<body class="Site">

  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Личный кабинет
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Личный кабинет</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
     {% if messages %}
            {% for message in messages %}
                <strong style="font-size: 40px; text-align:center; margin: 20px;" class="Profile-success">{{ message }}</strong>
            {% endfor %}
        {% endif %}
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Навигация
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'account' %}">Личный кабинет</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'profile' %}">Профиль</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'history_order' %}">История заказов</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Account">
            <div class="Account-group">
              <div class="Account-column">
                {%if profile.avatar%}
                <div class="Account-avatar"><img src='/media/{{profile.avatar}}' alt="card.jpg"/></div>
                {%else%}
                 <div class="Account-avatar"><img src="{% static 'assets/img/profile.png' %}" alt="card.jpg"/></div>
                {%endif%}
              </div>
              <div class="Account-column">
                <div class="Account-name">{{request.user.first_name}}
                </div><a class="Account-editLink" href="../profile">Редактировать профиль</a>
              </div>
            </div>
            <div class="Account-group">
              <div class="Account-column Account-column_full">
                <div class="Order Order_anons">
                  <div class="Order-personal">
                     {% if order %}
                    <div class="row">
                      <div class="row-block"><a class="Order-title" href="{% url 'oneorder' pk=order.id %}">Заказ&#32;<span class="Order-numberOrder">№{{order.id}}</span>&#32;от&#32;<span class="Order-dateOrder">{{order.created_at}}</span></a>
                        <div class="Account-editLink"><a href="{% url 'history_order' %}">История заказов</a>
                        </div>
                      </div>
                      <div class="row-block">
                        <div class="Order-info Order-info_delivery">
                          <div class="Order-infoType">Тип доставки:
                          </div>
                          <div class="Order-infoContent">{{order.delivery_method}}
                          </div>
                        </div>
                        <div class="Order-info Order-info_pay">
                          <div class="Order-infoType">Оплата:
                          </div>
                          <div class="Order-infoContent">{{order.payment_method}}
                          </div>
                        </div>
                        <div class="Order-info">
                          <div class="Order-infoType">Общая стоимость:
                          </div>
                          <div class="Order-infoContent">{{order.cart.final_price}}$
                          </div>
                        </div>
                        <div class="Order-info Order-info_status">
                          <div class="Order-infoType">Статус:
                          </div>
                          <div class="Order-infoContent">{{order.status}}
                          </div>
                        </div>
                         {%if order.status in not_pay%}
                       <div class="Order-info Order-info_error">
                      <div class="Order-infoType">Оплата не прошла:
                      </div>
                      <div class="Order-infoContent">Оплата не выполнена, т.к. вы подозреваетесь в нетолерантности
                      </div>
                    </div>
                      {%endif%}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                          {%endif%}
            </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
</body></html>

templates/users/historyorder.html
{% extends "header-footer.html" %}
{% load static%}
<!--END-->
<!--END--><!DOCTYPE html><!--[if IE 7]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> <html lang="ru"> <!--<![endif]-->
{% block header %}{% endblock header %}
{% block footer %}{% endblock footer %}
{% block content %}
<body class="Site">
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">История заказов
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>История заказов</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Навигация
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item"><a class="menu-link" href="../../users/account">Личный кабинет</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="../../users/profile">Профиль</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="../../users/history_order">История заказов</a>
                  </li>

                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Orders">
            {%for order in orders%}
            <div class="Order Order_anons">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block"><a class="Order-title"href="{% url 'oneorder' pk=order.id %}">Заказ&#32;<span class="Order-numberOrder">№{{order.id}}</span>&#32;от&#32;<span class="Order-dateOrder">{{order.created_at}}</span></a>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">Тип доставки:
                      </div>
                      <div class="Order-infoContent">{{order.delivery_method}}
                      </div>
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">Оплата:
                      </div>
                      <div class="Order-infoContent">{{order.payment_method}}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Общая стоимость:
                      </div>
                      <div class="Order-infoContent"><span class="Order-price">{{order.cart.final_price}}$</span>
                      </div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">Статус:
                      </div>
                      <div class="Order-infoContent">{{order.status}}
                      </div>

                    </div>
                     {%if order.status in not_pay%}
                       <div class="Order-info Order-info_error">
                      <div class="Order-infoType">Оплата не прошла:
                      </div>
                      <div class="Order-infoContent">Оплата не выполнена, т.к. вы подозреваетесь в нетолерантности
                      </div>
                    </div>
                      {%endif%}
                  </div>
                </div>
              </div>
            </div>
            {%endfor%}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
</body></html>

templates/users/login.html
{% extends "header-footer.html" %}
{% load static%}
<!--END-->
<!--END--><!DOCTYPE html><!--[if IE 7]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> <html lang="ru"> <!--<![endif]-->
{% block header %}{% endblock header %}
{% block footer %}{% endblock footer %}
{% block content %}
<body>
<div class="wrap">
  <h1>Страница входа</h1>
    {% if messages %}
            {% for message in messages %}
                <strong style="font-size: 20px; text-align:center; margin: 20px;" class="Profile-success">{{ message }}</strong>
            {% endfor %}
        {% endif %}
 <form class="form Profile-form"  method="post">
              {%csrf_token%}
              <div class="row">
                <div class="row-block">
                  <div class="form-group">
                    <label class="form-label" for="id_username">E-mail
                    </label>
                    <input class="form-input" id="id_username" name="username" type="text" maxlength="254" value="" data-validate="require"/>
                    {%if email%}
                    <div class="form-error">Пользователь с таким адресом уже существует</div>
                    {%endif%}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_password">Пароль
                    </label>
                    <input class="form-input" id="id_password" required name="password" autocomplete="new-password" type="password"/>
                  </div>
                  <div class="form-group">
                    <div class="Profile-btn">
                        {%if flag %}
                        <input type="hidden" name="next" value="/orders/order">
                        {%else%}
                        <input type="hidden" name="next" value="/">
                        {%endif%}
                      <button class="btn btn_success" type="submit">войти
                      </button>
                    </div>
<!--                    <div class="Profile-success">Профиль успешно сохранен-->
<!--                    </div>-->
                  </div>
                </div>
              </div>
            </form>
    <p style="font-size:22px">Забыли <a href="{% url 'restore_password' %}"> пароль?</a></p>
  <p style="font-size:22px">Если вы не зарегистрированы, то нужно <a href="{% url 'register' %}"> зарегистрироваться</a></p>
</div>
</body>
</html>
{% endblock content %}

templates/users/profile.html
{% extends "header-footer.html" %}
{% load static%}
<!--END--><!DOCTYPE html><!--[if IE 7]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> <html lang="ru"> <!--<![endif]-->
{% block header %}<{% endblock header %}
{% block footer %}<{% endblock footer %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src='{% static "assets/js/jquery-input-mask-phone-number.js" %}'></script>
<script>

            $(document).ready(function($) {
                $('#id_tel').usPhoneFormat({
                    format: 'xx(xxx) xxx-xxxx',
                });
            });

        </script>
<body class="Site">
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Профиль
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Профиль</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Навигация
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item"><a class="menu-link" href="../../users/account">Личный кабинет</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="../../users/profile">Профиль</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="../../users/history_order">История заказов</a>
                  </li>

                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Profile">
            <form class="form Profile-form" action="#" enctype="multipart/form-data" method="post">
              {%csrf_token%}
               <input style="display:none" class="form-input" id="id_username" name="username" maxlength="150" type="text" value="{{request.user.username}}" data-validate="require"/>
              <div class="row">
                <div class="row-block">
                  <div class="form-group">
                    <label class="form-label" for="avatar">Аватар
                    </label>
                    <div class="Profile-avatar Profile-avatar_noimg">
                      <div class="Profile-img"><img src='{% static "assets/img/#.png" %}' alt="#.png"/>
                      </div>
                      <label class="Profile-fileLabel" for="avatar">Выберите аватар
                      </label>
                      <input class="Profile-file form-input" id="avatar" name="avatar" type="file" data-validate="onlyImgAvatar"/>
                    </div>
                       {%if avatar_flag%}
                    <div class="form-error">Размер изображения не должен превышать 3Мб</div>
                    {%endif%}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_first_name">ФИО
                    </label>
                    <input class="form-input" id="id_first_name" name="first_name" maxlength="150" type="text" value="{{request.user.first_name}}"/>
                  </div>
                </div>
                <div class="row-block">
                  <div class="form-group">
                    <label class="form-label" for="id_tel">Телефон
                    </label>
                    <input class="form-input" id="id_tel" name="tel" value="+7{{cart.owner.tel}}" type="text" maxlength="14"/>
                     {%if phone%}
                    <div class="form-error">Пользователь с таким телефоном уже существует</div>
                    {%endif%}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_mail">E-mail
                    </label>
                    <input class="form-input" id="id_mail" name="email" type="text" maxlength="254" value="{{request.user.email}}" />
                     {%if email%}
                    <div class="form-error">Пользователь с таким адресом уже существует</div>
                    {%endif%}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_password1">Пароль
                    </label>
                    <input class="form-input" id="id_password1"   name="password1" autocomplete="new-password" type="password" placeholder="Тут можно изменить пароль"/>
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_password2">Подтверждение пароля
                    </label>
                    <input class="form-input" id="id_password2" name="password2"   type="password" placeholder="Введите пароль повторно"/>
                  </div>
                  <div class="form-group">
                    <div class="Profile-btn">
                      <button class="btn btn_success" type="submit">Сохранить
                      </button>
                    </div>
                    {%if flag%}
                    <div class="Profile-success">Профиль успешно сохранен</div>
                    {%endif%}
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
</body></html>

templates/users/register.html
{% extends "header-footer.html" %}
{% load static%}
<!--END-->
<!--END--><!DOCTYPE html><!--[if IE 7]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> <html lang="ru"> <!--<![endif]-->
{% block header %}{% endblock header %}
{% block footer %}{% endblock footer %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src='{% static "assets/js/jquery-input-mask-phone-number.js" %}'></script>
<script>

            $(document).ready(function($) {
                $('#id_tel').usPhoneFormat({
                    format: 'xx(xxx) xxx-xxxx',
                });
            });

        </script>
<body>
<div class="wrap">
  <h1>Страница регистрации</h1>
          {% if messages %}
            {% for message in messages %}
                <strong class="form-error">{{ message }}</strong>
            {% endfor %}
        {% endif %}
 <form class="form Profile-form"  method="post">
              {%csrf_token%}
              <div class="row">
                <input style="display:none" class="form-input" id="id_username" name="username" maxlength="150" type="text" value="user{{request.user.id}}" data-validate="require"/>
                <div class="row-block">
                  <div class="form-group">
                    <label class="form-label" for="id_first_name">ФИО
                    </label>
                    <input class="form-input" id="id_first_name" name="first_name" maxlength="150" type="text" value="" data-validate="require"/>
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_tel">Телефон
                    </label>
                    <input class="form-input" required id="id_tel" name="tel" value="+7" type="text" maxlength="14"/>
                    {%if phone%}
                    <div class="form-error">Пользователь с таким телефоном уже существует</div>
                    {%endif%}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_mail">E-mail
                    </label>
                    <input class="form-input" id="id_mail" name="email" type="text" maxlength="254" value="" data-validate="require"/>
                    {%if email%}
                    <div class="form-error">Пользователь с таким адресом уже существует</div>
                    {%endif%}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_password1">Пароль
                    </label>
                    <input class="form-input" id="id_password1" required name="password1" autocomplete="new-password" type="password"/>
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="id_password2">Подтверждение пароля
                    </label>
                    <input class="form-input" id="id_password2" name="password2" required type="password" placeholder="Введите пароль повторно"/>
                  </div>
                  <div class="form-group">
                    <div class="Profile-btn">
                      <button class="btn btn_success" type="submit">Зарегистрироваться
                      </button>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            </form>
</div>
</body>
</html>
{% endblock content %}

templates/users/restore_password.html
{% extends "header-footer.html" %}
{% load static%}
<!--END-->
<!--END--><!DOCTYPE html><!--[if IE 7]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> <html lang="ru"> <!--<![endif]-->
{% block header %}{% endblock header %}
{% block footer %}{% endblock footer %}
{% block content %}
<body>
<div class="wrap">
    <h1>Восстановление пароля</h1>
     <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn_success" type="submit">Восстановить пароль</button>
    </form>
</div>
</body>
</html>
{% endblock content %}